name: Compilation

on:
  push:
    branches: [ main ] 

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1

    - run: npm install

    - run: gulp build

    - uses: actions/upload-artifact@v1
      with:
        name: Monpackage
        path: dest
