# This is a basic workflow to help you get started with Actions

name: Exo1-jobs

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Bonjour"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - run: echo "Comment"
  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    steps:
    - run: echo "ca va ?"
  job4:
    runs-on: ubuntu-latest
    steps:
    - run: echo "vous"

  
