name: "triggers - exercice 3"
on:
  pull_request:
    paths:
    - "**.yml"
    - "!/test/**"
jobs:
  stale:
    runs-on: "ubuntu-latest"
    steps:
    - run: echo "je vérifgie les fichiers YAML"
    
